# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

from waflib import Utils

top = '..'

def build(bld):
    bld(features=['cxx', 'pch'],
        name='tests-base',
        target='tests-base',
        headers=['../src/common-pch.hpp', 'boost-test.hpp'],
        use='ndn-cxx',
        includes='.',
        )

    unit_tests = bld(
        target="unit-test-objects",
        name="unit-test-objects",
        features="cxx",
        source=bld.path.ant_glob(['unit-tests/**/*.cpp'],
                                 excl=['**/*-osx.cpp', '**/*-sqlite3.cpp']),
        use='tests-base',
        includes='.',
        install_path=None,
        )

    unit_tests_pib = bld(
        target="unit-test-pib-objects",
        name="unit-test-pib-objects",
        features="cxx",
        source=bld.path.ant_glob(['unit-tests-pib/**/*.cpp'],
                                 excl=['**/*-osx.cpp', '**/*-sqlite3.cpp']),
        use='tests-base pib-objects',
        includes='. ..',
        install_path=None,
        )

    integrated = bld(
        target="integrated-test-objects",
        name="integrated-test-objects",
        features="cxx",
        source=bld.path.ant_glob(['integrated/**/*.cpp'],
                                 excl=['**/*-osx.cpp', '**/*-sqlite3.cpp']),
        use='tests-base',
        includes='.',
        install_path=None,
        )

    objects = [(unit_tests, 'unit-tests'),
                (unit_tests_pib, 'unit-tests-pib'),
                (integrated, 'integrated')]
    for object in objects:
        if bld.env['HAVE_OSX_SECURITY']:
            object[0].source += bld.path.ant_glob(object[1] + '/**/*-osx.cpp')
        object[0].source += bld.path.ant_glob(object[1] + '/**/*-sqlite3.cpp')

    unit_test_main = bld(
        target='unit-tests-main',
        name='unit-tests-main',
        features='cxx',
        source=bld.path.ant_glob(['*.cpp']),
        use='ndn-cxx',
    )

    bld(features="cxx cxxprogram",
        target="../unit-tests",
        use="unit-test-objects unit-tests-main",
        install_path=None)

    bld(features="cxx cxxprogram",
        target="../unit-tests-pib",
        use="unit-test-pib-objects unit-tests-main",
        install_path=None)

    bld(features="cxx cxxprogram",
        target="../integrated-tests",
        use="integrated-test-objects unit-tests-main",
        install_path=None)
